import type { Request, Response } from "express";
import { Prisma, UserRole } from "../generated/prisma/client.js";
import { prisma } from "../config/database.js";

const id = (value: string | string[]): number | null => {
  if (typeof value !== "string") return null;
  const result = Number(value);
  return Number.isInteger(result) && result > 0 ? result : null;
};
const bodyId = (value: unknown): number | null => Number.isInteger(Number(value)) && Number(value) > 0 ? Number(value) : null;
const fail = (res: Response, message: string) => res.status(400).json({ success: false, message });
const notFound = (res: Response, message: string) => res.status(404).json({ success: false, message });

export const createCourse = async (req: Request, res: Response) => {
  const { name, code, teacher } = req.body as Record<string, unknown>;
  if (![name, code, teacher].every((item) => typeof item === "string" && item.trim())) return fail(res, "name, code, and teacher are required");
  try {
    const course = await prisma.course.create({ data: { name: (name as string).trim(), code: (code as string).trim().toUpperCase(), teacher: (teacher as string).trim() } });
    return res.status(201).json({ success: true, data: course });
  } catch (error) {
    if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") return res.status(409).json({ success: false, message: "Course code already exists" });
    throw error;
  }
};
export const updateCourse = async (req: Request, res: Response) => {
  const courseId = id(req.params.id); if (!courseId) return fail(res, "Invalid course ID");
  const { name, code, teacher } = req.body as Record<string, unknown>;
  if (name === undefined && code === undefined && teacher === undefined) return fail(res, "Provide a course field to update");
  if ([name, code, teacher].some((item) => item !== undefined && (typeof item !== "string" || !item.trim()))) return fail(res, "Course fields must be non-empty strings");
  try {
    const course = await prisma.course.update({ where: { id: courseId }, data: { ...(name !== undefined ? { name: (name as string).trim() } : {}), ...(code !== undefined ? { code: (code as string).trim().toUpperCase() } : {}), ...(teacher !== undefined ? { teacher: (teacher as string).trim() } : {}) } });
    return res.json({ success: true, data: course });
  } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2025") return notFound(res, "Course not found"); throw error; }
};
export const deleteCourse = async (req: Request, res: Response) => { const courseId = id(req.params.id); if (!courseId) return fail(res, "Invalid course ID"); try { await prisma.course.delete({ where: { id: courseId } }); return res.json({ success: true, message: "Course deleted", data: null }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2025") return notFound(res, "Course not found"); throw error; } };

export const createCourseOffering = async (req: Request, res: Response) => {
  const { courseId: rawCourseId, branch, semester, isRequired = true } = req.body as Record<string, unknown>; const courseId = bodyId(rawCourseId); const parsedSemester = Number(semester);
  if (!courseId || typeof branch !== "string" || !branch.trim() || !Number.isInteger(parsedSemester) || parsedSemester < 1 || typeof isRequired !== "boolean") return fail(res, "courseId, branch, positive semester, and boolean isRequired are required");
  try { const offering = await prisma.courseOffering.create({ data: { courseId, branch: branch.trim(), semester: parsedSemester, isRequired } }); return res.status(201).json({ success: true, data: offering }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") return res.status(409).json({ success: false, message: "Course offering already exists" }); throw error; }
};
export const updateCourseOffering = async (req: Request, res: Response) => { const offeringId = id(req.params.id); if (!offeringId) return fail(res, "Invalid course offering ID"); const { branch, semester, isRequired } = req.body as Record<string, unknown>; const parsedSemester = semester === undefined ? undefined : Number(semester); if (branch === undefined && semester === undefined && isRequired === undefined) return fail(res, "Provide an offering field to update"); if ((branch !== undefined && (typeof branch !== "string" || !branch.trim())) || (parsedSemester !== undefined && (!Number.isInteger(parsedSemester) || parsedSemester < 1)) || (isRequired !== undefined && typeof isRequired !== "boolean")) return fail(res, "Invalid offering fields"); try { const offering = await prisma.courseOffering.update({ where: { id: offeringId }, data: { ...(branch !== undefined ? { branch: branch.trim() as string } : {}), ...(parsedSemester !== undefined ? { semester: parsedSemester } : {}), ...(isRequired !== undefined ? { isRequired } : {}) } }); return res.json({ success: true, data: offering }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2025") return notFound(res, "Course offering not found"); throw error; } };
export const deleteCourseOffering = async (req: Request, res: Response) => { const offeringId = id(req.params.id); if (!offeringId) return fail(res, "Invalid course offering ID"); try { await prisma.courseOffering.delete({ where: { id: offeringId } }); return res.json({ success: true, message: "Course offering deleted", data: null }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2025") return notFound(res, "Course offering not found"); throw error; } };

const timetableData = (body: Record<string, unknown>) => { const courseOfferingId = bodyId(body.courseOfferingId); const dayOfWeek = Number(body.dayOfWeek); const { startTime, endTime, room, type } = body; if (!courseOfferingId || !Number.isInteger(dayOfWeek) || dayOfWeek < 1 || dayOfWeek > 7 || typeof startTime !== "string" || typeof endTime !== "string" || typeof room !== "string" || !/^\d{2}:\d{2}$/.test(startTime) || !/^\d{2}:\d{2}$/.test(endTime) || !room.trim() || (type !== undefined && type !== null && typeof type !== "string")) return null; return { courseOfferingId, dayOfWeek, startTime, endTime, room: room.trim(), type: type as string | null | undefined }; };
export const createTimetableEntry = async (req: Request, res: Response) => { const data = timetableData(req.body as Record<string, unknown>); if (!data) return fail(res, "Invalid timetable data; use HH:mm times and dayOfWeek 1-7"); const entry = await prisma.timetableEntry.create({ data }); return res.status(201).json({ success: true, data: entry }); };
export const updateTimetableEntry = async (req: Request, res: Response) => { const entryId = id(req.params.id); if (!entryId) return fail(res, "Invalid timetable ID"); const existing = await prisma.timetableEntry.findUnique({ where: { id: entryId } }); if (!existing) return notFound(res, "Timetable entry not found"); const data = timetableData({ ...existing, ...(req.body as Record<string, unknown>) }); if (!data) return fail(res, "Invalid timetable data"); const entry = await prisma.timetableEntry.update({ where: { id: entryId }, data }); return res.json({ success: true, data: entry }); };
export const deleteTimetableEntry = async (req: Request, res: Response) => { const entryId = id(req.params.id); if (!entryId) return fail(res, "Invalid timetable ID"); try { await prisma.timetableEntry.delete({ where: { id: entryId } }); return res.json({ success: true, message: "Timetable entry deleted", data: null }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2025") return notFound(res, "Timetable entry not found"); throw error; } };

const assignmentData = (body: Record<string, unknown>) => { const courseId = bodyId(body.courseId); const { title, description, duedate } = body; const due = new Date(String(duedate)); if (!courseId || typeof title !== "string" || !title.trim() || (description !== undefined && description !== null && typeof description !== "string") || Number.isNaN(due.getTime())) return null; return { courseId, title: title.trim(), description: description as string | null | undefined, duedate: due }; };
export const createAssignment = async (req: Request, res: Response) => { const data = assignmentData(req.body as Record<string, unknown>); if (!data) return fail(res, "courseId, title, and valid duedate are required"); const assignment = await prisma.assignment.create({ data }); return res.status(201).json({ success: true, data: assignment }); };
export const updateAssignment = async (req: Request, res: Response) => { const assignmentId = id(req.params.id); if (!assignmentId) return fail(res, "Invalid assignment ID"); const existing = await prisma.assignment.findUnique({ where: { id: assignmentId } }); if (!existing) return notFound(res, "Assignment not found"); const data = assignmentData({ ...existing, ...(req.body as Record<string, unknown>) }); if (!data) return fail(res, "Invalid assignment data"); const assignment = await prisma.assignment.update({ where: { id: assignmentId }, data }); return res.json({ success: true, data: assignment }); };
export const deleteAssignment = async (req: Request, res: Response) => { const assignmentId = id(req.params.id); if (!assignmentId) return fail(res, "Invalid assignment ID"); try { await prisma.assignment.delete({ where: { id: assignmentId } }); return res.json({ success: true, message: "Assignment deleted", data: null }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2025") return notFound(res, "Assignment not found"); throw error; } };

export const recordAttendance = async (req: Request, res: Response) => {
  const { userId: rawUserId, courseId: rawCourseId, present, date } = req.body as Record<string, unknown>; const userId = bodyId(rawUserId); const courseId = bodyId(rawCourseId); const attendanceDate = date === undefined ? new Date() : new Date(String(date));
  if (!userId || !courseId || typeof present !== "boolean" || Number.isNaN(attendanceDate.getTime())) return fail(res, "userId, courseId, present, and an optional valid date are required");
  const enrollment = await prisma.enrollment.findUnique({ where: { userId_courseId: { userId, courseId } } });
  if (!enrollment) return res.status(403).json({ success: false, message: "Student is not enrolled in this course" });
  const attendance = await prisma.attendance.create({ data: { userId, courseId, present, date: attendanceDate } }); return res.status(201).json({ success: true, data: attendance });
};

export const createEnrollment = async (req: Request, res: Response) => { const userId = bodyId((req.body as Record<string, unknown>).userId); const courseId = bodyId((req.body as Record<string, unknown>).courseId); if (!userId || !courseId) return fail(res, "userId and courseId are required"); const user = await prisma.user.findUnique({ where: { id: userId }, select: { branch: true, semester: true } }); if (!user?.branch || !user.semester) return fail(res, "Student needs a branch and semester"); const offering = await prisma.courseOffering.findUnique({ where: { courseId_branch_semester: { courseId, branch: user.branch, semester: user.semester } } }); if (!offering) return res.status(403).json({ success: false, message: "Course is not offered for the student's branch and semester" }); try { const enrollment = await prisma.enrollment.create({ data: { userId, courseId } }); return res.status(201).json({ success: true, data: enrollment }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") return res.status(409).json({ success: false, message: "Student is already enrolled" }); throw error; } };
export const deleteEnrollment = async (req: Request, res: Response) => { const enrollmentId = id(req.params.id); if (!enrollmentId) return fail(res, "Invalid enrollment ID"); try { await prisma.enrollment.delete({ where: { id: enrollmentId } }); return res.json({ success: true, message: "Enrollment deleted", data: null }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2025") return notFound(res, "Enrollment not found"); throw error; } };

export const assignFacultyToCourse = async (req: Request, res: Response) => { const facultyId = bodyId((req.body as Record<string, unknown>).facultyId); const courseId = bodyId((req.body as Record<string, unknown>).courseId); if (!facultyId || !courseId) return fail(res, "facultyId and courseId are required"); const faculty = await prisma.user.findUnique({ where: { id: facultyId }, select: { role: true } }); if (faculty?.role !== UserRole.FACULTY) return fail(res, "facultyId must identify a faculty user"); try { const assignment = await prisma.facultyCourse.create({ data: { facultyId, courseId } }); return res.status(201).json({ success: true, data: assignment }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") return res.status(409).json({ success: false, message: "Faculty member is already assigned to this course" }); throw error; } };
export const removeFacultyFromCourse = async (req: Request, res: Response) => { const assignmentId = id(req.params.id); if (!assignmentId) return fail(res, "Invalid faculty course assignment ID"); try { await prisma.facultyCourse.delete({ where: { id: assignmentId } }); return res.json({ success: true, message: "Faculty course assignment deleted", data: null }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2025") return notFound(res, "Faculty course assignment not found"); throw error; } };
